// <auto-generated/>

using System.Reflection;
using CryptoPunks.MoreTech.Api.DataAccess.Extensions;
using CryptoPunks.MoreTech.Platform.Data.Extensions;
using CryptoPunks.MoreTech.Platform.Data.FluentMigrator;
using CryptoPunks.MoreTech.Platform.Extensions;
using MediatR;

var builder = WebApplication
    .CreateBuilder(args)
    .UsePlatform();
var services = builder.Services;

#region DI

services.AddControllers();
services.AddEndpointsApiExplorer();
services.AddSwagger("more-tech-api");
services.AddSerilogLogger();
services.AddDataAccess();
services.AddMediatR(Assembly.GetExecutingAssembly());

#endregion

var app = builder.Build();

#region App

app.UseSwagger();
app.UseSwaggerUI();
app.MapControllers();

#endregion

await app.RunOrMigrateAsync(args);
