// <auto-generated/>
using FluentMigrator;
using FluentMigrator.Oracle;
using FluentMigrator.Postgres;

namespace CryptoPunks.MoreTech.Api.DataAccess.Migrations;

[Migration(1)]
public class JobTitlesMigration : ForwardOnlyMigration
{
    public override void Up()
    {
        var dataToMigrate = new
        {
            name = "Главный по главным",
            description = "???"
        };
        Insert
            .IntoTable("job_titles")
            .Row(dataToMigrate);
    }
}
