// <auto-generated/>
using FluentMigrator;

namespace CryptoPunks.MoreTech.Api.DataAccess.Migrations;

[Migration(2)]
public class NftMigration : ForwardOnlyMigration
{
    public override void Up()
    {
        Create.Table("nft_index").WithDescription("")
            .WithColumn("url").AsString()
            .WithColumn("token_id").AsInt64()
            .WithColumn("price").AsDecimal();

        Create.UniqueConstraint("consatraint_url_token").OnTable("nft_index")
            .Columns("url", "token_id");

        Alter.Table("users")
            .AddColumn("level").AsInt32().WithDefaultValue(1)
            .AddColumn("points").AsInt32().WithDefaultValue(0);
    }
}
